### PR TITLE
[ADD][8.0]Jalali date support

### PR DESCRIPTION
**Pull request by elicoidal**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why _printout suffix? Shouldn't this be `web_widget_date_jalali`? Shouldn't this be attached to user lang?

**Comment by elicoidal** [comment]
@pedrobaeza 
I pushed some old modules that we did for a project in Iran in order to share the knowledge.
I am not sure the way it has been implemented is the best but I will not invest more time on it (other than fixing Travis).
If you think it is not valid enough I can publish it in our company repo which is less strict but I though it nice for the Persian community to have some modules to get started with.
As said I am open :smile:

**Comment by pedrobaeza** [comment]
Well, I don't have interest in this as we don't have any customer in Iran, but just saying, at least, things to add to "Known issues". I won't block of course if they are not developped, as this better than having nothing.

About the name, it's important to have the best proper one, but I don't know also the implementation, so my name is just a suggestion about what I think it does.

**Comment by elicoidal** [comment]
@pedrobaeza 

I can improve the naming removing the _printout (but I dont think web_widget_ is relevant as this is much simpler than that: replacing date fields function in some printouts).

I will add some text to the known issues such as well.
Thanks for your input!

**Comment by elicoidal** [comment]
closing wrong branch!

**Pull request closed without merging**
